### ISSUE TITLE
set-cvms does not process all clusters by default

### ISSUE THREAD

**Issue by BristleBeard** [sbourdeaud/nutanix#2]
`set-cvms.ps1` has noted within that by default it will process all clusters in vCenter. I don't see that this is currently possible, as the cluster(s) are only defined by a `Read-host` command.

**Comment by sbourdeaud** [comment]
You're right. At some point I must have coded to process all clusters by default then later changed it.  I prefer to leave it with having to specify the cluster so I simply updated the online help.
