### ISSUE TITLE
set-hostconfig.ps1 -clearntp switch does not clear ntp configs

### ISSUE THREAD

**Issue by just-broome** [sbourdeaud/nutanix#3]
script: set-hostconfig.ps1
switch: clearntp
issue: does not clear previously configured ntp settings prior to setting new ntp configs; no errors are reported; and success **is** reported.

ALSO

connect-viserver w/o -force switch does not connect to vCenter and neither the set-cvms nor set-hostconfig scripts report an error.

**Comment by sbourdeaud** [comment]
David, I'm already using a try and catch statement, so this is an issue with the VMware API saying it cleared ntp settings successfully when it really did not...
Regarding connect-viserver, if you are using self-signed certificates, you need to change the powercli behavior to accept those by default.
Errors are suppressed by default, unless you use the -debugme parameter.  I need to make this better which I have started to do in newer scripts.
