### ISSUE TITLE
Backup AHV VM script error 500

### ISSUE THREAD

**Issue by Ridddick** [sbourdeaud/nutanix#4]
Hi! Sorry for disturbing but i'm stuck while testing your backup script for AHV. All prerequicities were made as you had offered in comments. Hope you'll help me to find what i'm missing.
The debug output:

PS /home/user/Desktop> ./backup-ahvVm.ps1 -debugme -cluster 10.0.0.33 -username admin -password pass -vms Veeam-Availability-AHV -proxy "AHV-bak" -backupPath  /media/bak     
03/07/2019 19:15:30 [INFO] Checking the Powershell version...
03/07/2019 19:15:30 [INFO] Checking for required Powershell modules...
03/07/2019 19:15:30 [INFO] Disabling Tls...
03/07/2019 19:15:30 [INFO] Enabling Tls 1.2...
03/07/2019 19:15:30 [INFO] Retrieving list of VMs...
03/07/2019 19:15:30 [SUCCESS] Successfully retrieved VMs list from 10.0.0.33!
03/07/2019 19:15:30 [INFO] Retrieving the list of networks on 10.0.0.33...
03/07/2019 19:15:30 [SUCCESS] Successfully retrieved the list of networks on 10.0.0.33!
03/07/2019 19:15:30 [INFO] Saving 10.0.0.33 networks information to /media/bak/10.0.0.33_networks.json...
03/07/2019 19:15:30 [INFO] Asking for snapshot id allocation for AHV-bak...
03/07/2019 19:15:30 [SUCCESS] Successfully obtained a snapshot id allocation!
03/07/2019 19:15:30 [SUCCESS] Veeam-Availability-AHV exists on 10.0.0.33!
03/07/2019 19:15:30 [INFO] Retrieving the configuration of Veeam-Availability-AHV...
03/07/2019 19:15:30 [SUCCESS] Successfully retrieved the configuration of Veeam-Availability-AHV...
03/07/2019 19:15:30 [DEBUG] vmConfig: @{allow_live_migrate=True; gpus_assigned=False; ha_priority=0; memory_mb=4096; name=Veeam-Availability-AHV; num_cores_per_vcpu=2; num_vcpus=2; power_state=off; timezone=UTC; uuid=17e9d359-45fa-4caa-ba36-c9b03d820013; vm_disk_info=System.Object[]; vm_features=; vm_logical_timestamp=5; vm_nics=System.Object[]}
03/07/2019 19:15:30 [INFO] Saving Veeam-Availability-AHV configuration to /media/bak/Veeam-Availability-AHV.json...
03/07/2019 19:15:30 [INFO] Creating a crash consistent snapshot of vm Veeam-Availability-AHV...
03/07/2019 19:15:30 [INFO] Retrieving status of snapshot backup.snapshot.2019_03_07_19_15_Veeam-Availability-AHV ...
03/07/2019 19:15:30 [DEBUG] snapshotStatus.status: @{state=RUNNING; execution_context=}
03/07/2019 19:15:30 [WARNING] backup.snapshot.2019_03_07_19_15_Veeam-Availability-AHV status is RUNNING, waiting 5 seconds...
03/07/2019 19:15:36 [DEBUG] snapshotStatus.status: @{name=backup.snapshot.2019_03_07_19_15_Veeam-Availability-AHV; snapshot_file_list=System.Object[]; snapshot_type=CRASH_CONSISTENT; state=COMPLETE; expiration_time_msecs=3699451778788; execution_context=; resources=}
03/07/2019 19:15:36 [SUCCESS] backup.snapshot.2019_03_07_19_15_Veeam-Availability-AHV status is COMPLETE!
03/07/2019 19:15:36 [DEBUG] snapshotStatus.status.snapshot_file_list: @{file_path=/ISO/.acropolis/vmdisk/cfd5982d-33c2-41ea-aa50-f54aaa16c460; snapshot_file_path=/ISO/.snapshot/07/829977482284098730-1524876925442485-10807/.acropolis/vmdisk/cfd5982d-33c2-41ea-aa50-f54aaa16c460}
03/07/2019 19:15:36 [INFO] Mounting the Veeam-Availability-AHV snapshots on AHV-bak...
03/07/2019 19:15:36 [DEBUG] vmConfig.vm_disk_info: @{disk_address=; is_cdrom=False; is_empty=False; flash_mode_enabled=False; is_scsi_passthrough=True; is_thin_provisioned=False; shared=False; source_disk_address=; storage_container_uuid=dabf2d45-6481-4e04-8776-5c671179244d; size=53687091200}
03/07/2019 19:15:36 [DEBUG] snashotFile.file_path: /ISO/.acropolis/vmdisk/cfd5982d-33c2-41ea-aa50-f54aaa16c460
03/07/2019 19:15:36 [DEBUG] diskToAttachRef: System.Collections.Hashtable
03/07/2019 19:15:36 [DEBUG] diskToAttachRefArray: 
03/07/2019 19:15:36 [DEBUG] JSON body: {
  "vm_disks": [
    {
      "vm_disk_clone": {
        "disk_address": {
          "ndfs_filepath": "/ISO/.snapshot/07/829977482284098730-1524876925442485-10807/.acropolis/vmdisk/cfd5982d-33c2-41ea-aa50-f54aaa16c460",
          "device_bus": "SCSI"
        }
      }
    }
  ],
  "uuid": ""
}
03/07/2019 19:15:36 [ERROR] Response status code does not indicate success: 500 (Internal Server Error).
03/07/2019 19:15:36 [ERROR] Could not retrieve full REST error details.

**Comment by sbourdeaud** [comment]
Apologies, just saw this here as I was browsing my github...
Looks like it is failing to attach the snapshot as an additional disk to your VM.  I see your VM is called veeam availability for AHV, which is itself a backup product.
Are you able to add manually additional disks to that VM in Prism?  Why are you using my script in a Veeam VM?
